CREATE TABLE IF NOT EXISTS dws_shop_info_combine_v8(
	shop_id BIGINT COMMENT '店铺ID',
	 shop_name STRING COMMENT '店铺名',
	 shop_name_bak STRING,
	 shop_url STRING COMMENT '店铺URL',
	 seller_id BIGINT COMMENT '卖家ID',
	 seller_name STRING COMMENT '卖家名',
	 rank BIGINT COMMENT '店铺等级（几个图标，1-6）',
	 rank_type BIGINT COMMENT '店铺等级类型:4-金冠;3-皇冠;2-钻石;1-红心',
	 main_industry STRING COMMENT '爬虫主营行业，会废弃',
	 from_place STRING COMMENT '店铺所在地',
	 fans_num STRING COMMENT '粉丝数',
	 rate_url STRING COMMENT '淘宝掌柜url',
	 good_comment_rate DOUBLE COMMENT '好评率',
	 `status` BIGINT COMMENT '店铺状态（0-无效，1-有效）',
	 label_industry STRING COMMENT '人工标注的行业信息',
	 label_type STRING COMMENT '人工标注的店铺类型',
	 label_style STRING COMMENT '人工标注的店铺风格',
	 label_price_level STRING COMMENT '人工标注的价位',
	 total_sales_volume BIGINT COMMENT '店铺总销售量',
	 total_sale BIGINT COMMENT '店铺总销售额',
	 total_item_amount BIGINT COMMENT '店铺总商品数',
	 shop_type STRING COMMENT '是否为天猫(0: 淘宝，1:天猫)',
	 shop_sale_type BIGINT COMMENT '是否为平销店铺(0:是, 1:不是, 2:未参与计算)',
	 shop_level BIGINT COMMENT '店铺对标人群(5:高消费, 4:中高消费, 3:中消费, 2:中低消费, 1:低消费, 0:未参与计算)',
	 shop_agency_type BIGINT COMMENT '是否为代购(0:不是，1:是)',
	 shop_agency_country STRING COMMENT '店铺代购的国家名称',
	 crawl_time DATETIME COMMENT '爬虫开始爬取时间',
	 origin_shop_name STRING COMMENT '备份shop_name，用于ads不添加全文索引',
	 fans_num_no_unit BIGINT COMMENT '去除单位的店铺粉丝数',
	 not_show_sale_flag BIGINT COMMENT '店铺是否展示销量标记,0：展示，1:店铺隐藏销量',
	 has_item_daily_data BIGINT COMMENT '0:无，1:有商品每日销量',
	 describe_info STRING COMMENT '宝贝、物流、态度描述',
	 is_hydc_shop BIGINT COMMENT '1:是，0不是。保存最新店铺范围',
	 crawl_important_status BIGINT COMMENT '1:是（包含历史行业洞察店铺+用户监控和历史收录过），0不是',
	 shop_logo STRING,
	 treasure_shop BIGINT COMMENT '1:是，0不是。是否为宝藏店铺',
	 item_avg_price BIGINT COMMENT '商品平均价格',
	 open_status BIGINT) ROW FORMAT SERDE 'com.aliyun.apsara.serde.AliOrcSerDe' 
TBLPROPERTIES ('comment'='*');