CREATE TABLE IF NOT EXISTS item_info_combine_v2(
	item_id BIGINT COMMENT '商品id',
	 title STRING COMMENT '商品名',
	 pic_url STRING COMMENT '主图url',
	 pic_url_list STRING COMMENT '轮播图url',
	 category_id BIGINT COMMENT '品类id',
	 category_name STRING COMMENT '品类名',
	 root_category_id BIGINT COMMENT '根目录id',
	 shop_id BIGINT COMMENT '店铺id',
	 sale_time DATETIME COMMENT '上新时间',
	 cprice BIGINT COMMENT '促销价',
	 sprice BIGINT COMMENT '原价',
	 collect BIGINT COMMENT '商品收藏量',
	 comment_count BIGINT COMMENT '商品评论数',
	 shelves BIGINT COMMENT '商品上架状态：0 下架不可看，1-正常，2-下架可访问，3-预售',
	 first_day_sales_volume BIGINT COMMENT '首日销量',
	 first_day_sale BIGINT COMMENT '首日销售额',
	 first_week_sales_volume BIGINT COMMENT '首周销量',
	 first_week_sale BIGINT COMMENT '首周销售额',
	 first_month_sales_volume BIGINT COMMENT '首月销量',
	 first_month_sale BIGINT COMMENT '首月销售额',
	 pic_oss_url STRING,
	 pic_detail_oss_url STRING,
	 min_price BIGINT COMMENT '历史最低价格',
	 first_day_collect BIGINT COMMENT '首日搜藏量',
	 sale_day BIGINT COMMENT '当日销量（昨日）',
	 sale_7day BIGINT COMMENT '近7日销量',
	 sale_30day BIGINT COMMENT '近30天销量',
	 sale_30day_insert_time DATETIME COMMENT '近30天销量插入时间',
	 total_sale_volume BIGINT COMMENT '总销量',
	 total_sale_amount BIGINT COMMENT '总销售额',
	 first_insert_time DATETIME COMMENT '商品首次插入时间',
	 title_status BIGINT COMMENT ' title是否有效标识别，1:有效，0:无效',
	 video_url STRING COMMENT '视频链接',
	 min_bad_rate DOUBLE COMMENT '历史最小差评率',
	 max_bad_rate DOUBLE COMMENT '历史最大差评率',
	 bad_rate DOUBLE COMMENT '目前差评率',
	 `properties` STRING COMMENT '属性信息',
	 bad_comment_count BIGINT COMMENT '差评数',
	 max_cprice BIGINT COMMENT '售价最高价',
	 max_sprice BIGINT COMMENT '划线价（原价）最高价',
	 presale_price BIGINT COMMENT '定金',
	 ordered_item_volume BIGINT COMMENT '下定金的商品销量',
	 presale_status BIGINT COMMENT '定金预售状态：1、2：预售中  3:预售结束',
	 presale_start_time DATETIME COMMENT '交定金开始的时间',
	 presale_end_time DATETIME COMMENT '交定金结束的时间',
	 presale_promotion STRING COMMENT '额外参与的活动',
	 withdrawal_date DATETIME COMMENT '最新下架时间',
	 favor_num BIGINT COMMENT '爆款系数',
	 max_day_volumn BIGINT COMMENT '最大日销量',
	 max_volume_date DATETIME COMMENT '最大日销量的日期',
	 is_mall_item BIGINT COMMENT '是否为商场同款',
	 delivery_from STRING COMMENT '发货地',
	 row_key STRING COMMENT 'item_id的reverse值',
	 first_day_stock BIGINT COMMENT '上新首日库存量',
	 start_sell_volume BIGINT COMMENT '开卖当天销量',
	 start_sell_date STRING COMMENT '开卖当天日期',
	 new_flag BIGINT COMMENT '爬取到的新品标记',
	 start_sell_stock BIGINT COMMENT '开卖当日库存',
	 history_min_left_cprice BIGINT COMMENT '最低价左区间',
	 history_min_right_cprice BIGINT COMMENT '最低价右区间',
	 history_min_cprice_date DATETIME COMMENT '最低价卖售最新时间',
	 full_advance_sale BIGINT COMMENT '全款预售 1是全款预售',
	 nearly_sale_time DATETIME COMMENT '最近上架时间',
	 upper_shelves_num BIGINT COMMENT '商品截止到当前，一共上架的次数',
	 first_day_sku_num BIGINT COMMENT '首日SKU数',
	 start_sell_amount BIGINT COMMENT '开卖首日销售额',
	 start_sell_sku_num BIGINT COMMENT '开卖首日SKU数',
	 sale_time_7day_volume BIGINT COMMENT '上新7天销量',
	 sale_time_7day_amount BIGINT COMMENT '上新7天销售额',
	 sale_time_30day_collect BIGINT COMMENT '上新30天收藏',
	 sale_time_7day_collect BIGINT COMMENT '上新7天收藏',
	 start_sell_avg_volume DOUBLE COMMENT '店铺开卖当天平均销量',
	 history_max_left_cprice BIGINT COMMENT 'cprice最高价',
	 history_max_cprice_date DATETIME COMMENT 'cprice最高价最新时间',
	 ordered_item_amount BIGINT COMMENT '下定金的商品销售额',
	 usual_cprice BIGINT COMMENT '常卖价',
	 coupon_cprice BIGINT COMMENT '最新券后价',
	 sku_cnt BIGINT COMMENT 'sku数量') 
CLUSTERED BY ( shop_id ASC) SORTED BY (shop_id ASC) INTO 1024 BUCKETS ROW FORMAT SERDE 'com.aliyun.apsara.serde.AliOrcSerDe' 
TBLPROPERTIES ('comment'='淘宝商品信息数据合并表用于同步');